### ISSUE TITLE
CheckBox

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10.Tests.Browser#10]
Методы для проверки отмечен/не отмечен.

**Comment by alex-kukhtin** [comment]
<CheckBox Label="" TestId="">
   <Unchecked/>
   <Check />
   <Checked/>
   <Uncheck/>
   <Unchecked/>
</CheckBox>

**Comment by alex-kukhtin** [comment]
<CheckBox Label="З ПДВ">
				<Unchecked/>
				<Check />
				<Checked />
				<Uncheck/>
				<Unchecked/>
			</CheckBox>
