### ISSUE TITLE
Panel.Open

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10.Tests.Browser#13]
`<Panel Header="@[Memo]..." Style="Cut" Collapsible="True" Collapsed="True" TestId="MemoPanel">
			<TextBox Multiline="True" AutoSize="True" Value="{Bind Document.Memo}" Rows="3" UpdateTrigger="Input" TestId="MemoTextBox"/>
		</Panel>`

Открыть панель для того, чтобы внести значение в TextBox.

**Comment by alex-kukhtin** [comment]
<Panel TestId="MemoPanel">
				<Open />
			</Panel>
