### ISSUE TITLE
TabPanel

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10.Tests.Browser#14]
`<TabPanel Padding="0">
			<Tab Header="ТМЦ" Padding=".05rem,0,0,0" Badge="{Bind Document.Rows.length, DataType=Number, HideZeros=True}">`

Нужна возможность пепреключения закладок.

**Comment by alex-kukhtin** [comment]
<TabPanel>
				<Tab Header="Витрати"></Tab>
			</TabPanel>
