### ISSUE TITLE
Button.DropDown

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10.Tests.Browser#17]
![image](https://user-images.githubusercontent.com/35917940/70042934-6af05800-15c8-11ea-84f3-49fb507a28c1.png)

`<Button.DropDown>
						<DropDownMenu Separate="True">
							<MenuItem Icon="Import" Content="@[Add]" Tip="@[AddFromCatalog]"
									  Command="{BindCmd Execute, CommandName=ImportFromCatalog, Argument={Bind Currencies}, CheckReadOnly=True}"/>
						</DropDownMenu>
					</Button.DropDown>`

Нужно кликнуть на "клювик".

**Comment by alex-kukhtin** [comment]
version 7026
```xml
<Scenario Name="Перевірка додавання із довідника">
	<Button Text="Нова валюта">
		<ClickCaret/>
	</Button>
	<DropDown>
		<ClickMenuItem Text="Додати"/>
	</DropDown>
	<Dialog Title="Вибір валюти">
		<Escape />
	</Dialog>
</Scenario>
```
