### ISSUE TITLE
ListItem. ClickButton

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10.Tests.Browser#18]
`<List TestId="Contracts">
			<ListItem Header="Придбання № 11111111/1 від 01.01.2019">
				<ClickButton Icon="Edit"/>
			</ListItem>
		</List>`

Ошибка: no such element: Unable to locate element: {"method":"xpath","selector":".//button[contains(@class,'btn')]/i[contains(@class, 'ico-edit')]"}

**Comment by alex-kukhtin** [comment]
Done (7027)
