### ISSUE TITLE
NewWindow. Url

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10.Tests.Browser#19]
Нужно в Url передать идентификатор. К примеру: /reports/contract/turnoversheetdatedocument361/new?Contract=926

**Comment by alex-kukhtin** [comment]
/blablabla[[Id]]
А чтобы получить Id - ModelValue.
Начиная с 7027 работает и для основной модели.
Можно посмотреть в Договора\Звіти
