### ISSUE TITLE
Окно печати не закрывается

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10.Tests.Browser#2]
Выполняется команда:
Command="{BindCmd Report, Report=documentlist, Argument='0', Data={Bind Root.$RepListData}, Print=True}"

В сценарии:
		ClickButton Text="Надрукувати"
		Escape
Окно печати не закрывается ни по Escape, ни по ClickButton в нём

**Comment by alex-kukhtin** [comment]
<ClickButton Text="Надрукувати"/>
<PrintWindow>
     <CancelPrint />
</PrintWindow>
