### ISSUE TITLE
DatePicker. TestId

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10.Tests.Browser#21]
Не устанавливается TestId
`<DatePicker Value="{Bind Document.Date}" Align="Left" Bold="True" Placement="BottomRight"
									TestId="Date" If="{Bind Document.$IsCredit}"/>`

Tests\02 Документи\01 Запаси\02 Прибуткова накладна\05 Створення податкового кредиту.feature.xaml

**Comment by alex-kukhtin** [comment]
v 7601
