### ISSUE TITLE
PropertyGridItem. EnsureText

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10.Tests.Browser#23]
Нужно проверить текст. К примеру, в той же Налоговой проверить "Операція":
![image](https://user-images.githubusercontent.com/35917940/71105621-8e212700-21c6-11ea-9fdc-e2dcdc944b52.png)

Tests\02 Документи\01 Запаси\02 Прибуткова накладна\05 Створення податкового кредиту.feature.xaml

**Comment by alex-kukhtin** [comment]
Done (7030)
```xml
<PropertyGrid TestId="PropGridInfo">
	<PropertyGridItem Name="Операція" Value="Придбання матеріальних активів"/>
	<PropertyGridItem Name="Код" Value="Новий"/>
</PropertyGrid>
