### ISSUE TITLE
Combobox. Выбор элемента

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10.Tests.Browser#25]
Выбрать элемент, в наименовании которого есть одинарная кавычка. Пример:
`<ComboBox TestId="DocVATRate">
				<Click/>
				<Select Text="Ставка з властивостей об'єкта"/>
			</ComboBox>`

02 Документи - 01 Запаси - 03 Прибуткова податкова накладна - 05 Зміна ставок ПДВ.feature

**Comment by alex-kukhtin** [comment]
v 7030
