### ISSUE TITLE
Кликнуть Hyperlink с командой

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10.Tests.Browser#7]
`<Hyperlink Content="@[CreateBankPayment]" Icon="File" Size="Small" Block="True" If="{Bind Document.$CanPayment}"
								   Command="{BindCmd Execute, CommandName='createBankPayment', Argument={Bind Document}}"/>`

**Comment by alex-kukhtin** [comment]
Команд в html нету. Можно определить ссылку через Icon, Text, TestId
